def string_construction(string)
  string.chars.uniq.size
end

puts string_construction("cbabbbababdcadabbcbcbacbbadaadbbdcdcbdaadbcbccccbdbbcbaaabbaacbbaabcbacadcaaabbcacdaaacdcaaccbdadaccdacbabdcbcdacbbddcdbbbcaaadacdaacdbacccbabcbdabbbadaccaaababcaabaccaabacdbcababbbaddccaccddadacccbcbbddcbccbcaadbcbbdcbcadaddbbbadbbccadcbddadcacacdcaacccdbdccacbddacacacdcbaadcbdaacbddcbbcbacbbabdacacccbbaccdccbbccacbdaadcbdcabbcdbbabcbdbddcbddcadbaacbbcdcacadbaadcbbcaddbbcbadddcabadbdbadcabbacaddbbdddbdaacddccdcdaccadadbaacddabbbddacbccbbcaabacaaddccccddaabbcacbccbbdddadaccdadbcabbabdbbcbbdbcdbcbcccdbbcdbdbdc").inspect # 4
